### ISSUE TITLE
flutter commands start up slowly

### ISSUE THREAD

**Issue by devoncarew** [flutter/tools#105]
The flutter / sky_tools commands seem to have a fixed cost to how long they take to run. Even something like `pub run flutter list -h` always takes a min. of 1.2 seconds.

From Atom, I run:

```
pub run flutter stop
pub run flutter start
pub run flutter logs
```

sequentially, to start an app. This takes ~2.4 seconds to fail if there are no devices connected, and ~3.6 seconds to print the first bit of output from the device if we are able to launch. We should measure where the time is being spent, but it would be nice if launches were faster (both hot and cold launches).

**Comment by abarth** [comment]
Is this command using the snapshot?

```
$ time pub run flutter list -h
real	0m1.677s
$ time flutter list -h
real	0m0.159s
```

For some reason, the second version is 10x faster than the first.

**Comment by devoncarew** [comment]
My initial timings were from a local package override. The new ones:
```
[~/flutter/long_scene_3943] time pub run flutter list -h
real	0m0.424s
user	0m0.395s
sys	0m0.068s

[~/flutter/long_scene_3943] time flutter list -h
real	0m0.110s
user	0m0.103s
sys	0m0.018s
```

So, faster than before. It looks like the overhead is in `pub run`. `pub run` is more reliable for me to drive from atom as I don't have to assume that the user's path is set up with the pub bin path.

**Comment by devoncarew** [comment]
Closing. I think the slowness is in `pub run`. We can re-visit if it turns out this is the gating factor for fast launch from atom.
