### ISSUE TITLE
clarify what we're using logging for

### ISSUE THREAD

**Issue by devoncarew** [flutter/tools#106]
Are we using logging for diagnostics for users, or to emit stdout and stderr info to users? It seems like we're doing a little of both.

**Comment by abarth** [comment]
I'm not sure I understand the difference.

**Comment by devoncarew** [comment]
I mostly meant that some messages to stdout we should always write, regardless of the logging level. Like `Starting compile...` and `Compiled 8 files.`. And some failures in commands should always be emitted to stderr (`App launch failure`). And the logging should mostly be used to record a record of what the tool was doing, that could be useful for diagnosing where in the process it's failing when things go wrong.

Right now we're emitting some status and command failures to logging, when I think they should instead go to stdout or stderr.

I'll close this issue and call out individual cases when I hit them -

**Comment by abarth** [comment]
Ok.  Happy to do whatever you think is best.
