### ISSUE TITLE
early calls to `exit()`

### ISSUE THREAD

**Issue by devoncarew** [flutter/tools#107]
There are some early calls to `exit(int)`. We should probably throw at these locations, or pass back an exit status code through the `Future<int> run()` methods.

https://github.com/flutter/tools/blob/master/lib/src/commands/flutter_command_runner.dart#L120

**Comment by abarth** [comment]
What should we throw?

**Comment by devoncarew** [comment]
Don't know; something that'll bubble up to the main call to `exit()` (https://github.com/flutter/tools/blob/master/lib/executable.dart#L60). This is happening in a getter (`buildConfigurations`) - those should be largely side-effect free.

Happy to take this on my next pass through this tool.

**Comment by abarth** [comment]
SGTM
