### ISSUE TITLE
Update to the 0.12.5+1 version of `test`

### ISSUE THREAD

**Issue by Hixie** [flutter/tools#132]

**Comment by devoncarew** [comment]
I think the code in `lib/src/test` is not happy with the change from using `test` `0.12.4+9` to `0.12.5+1`.

**Comment by devoncarew** [comment]
`Test.change()` is gone; `filter()` and `forPlatform()` (abstract methods) were added.

Some changes are here: https://github.com/dart-lang/test/commit/a9cfdc138e0873fd660ba015db2f5a12de325616#diff-21b32fc79cc5c0d3aa35bbf2d624717b. That may or may not capture all of them.

@abarth, I think this'll need some updating. Probably good incentive to push for a public test API -

**Comment by devoncarew** [comment]
Also cc @nex3 - do you have some pointers for what we'll need to update when moving to the latest `test`?

```
[warning] The named parameter 'metadata' is not defined at lib/src/test/loader.dart, line 143.
[warning] The getter 'tests' is not defined for the class 'Declarer' at lib/src/test/remote_listener.dart, line 87.
[warning] The named parameter 'metadata' is not defined at lib/src/test/remote_listener.dart, line 88.
[warning] The getter 'tests' is not defined for the class 'Suite' at lib/src/test/remote_listener.dart, line 104.
[warning] The getter 'tests' is not defined for the class 'Suite' at lib/src/test/remote_listener.dart, line 105.
[warning] The getter 'tests' is not defined for the class 'Suite' at lib/src/test/remote_listener.dart, line 121.
[warning] Missing concrete implementation of 'Test.filter' and 'Test.forPlatform' at lib/src/test/remote_test.dart, line 17.
```

**Comment by abarth** [comment]
Yeah, we're poke a lot of internal details of the test package, which is why we had the tight version constraint.  Really we need a public API for doing what we're doing.

**Comment by devoncarew** [comment]
fixed in https://github.com/flutter/tools/pull/143
