### ISSUE TITLE
sky_tools run_mojo in checked mode

### ISSUE THREAD

**Issue by afandria** [flutter/tools#53]
I've been using `pub run sky_tools run_mojo`. I like how I can pass extra arguments like `--enable-multiprocess` and `--map-origin` to the mojo shell.

I would also like to pass the `--checked` flag to my Sky/Flutter app. Can this option be added?

@jamesr

**Comment by jamesr** [comment]
You can append the incantation `--args-for="mojo:sky_viewer --enable-checked-mode"` to get this behavior today.  I'll add a nicer interface for this to run_mojo itself so you don't have to remember all this stuff.

**Comment by afandria** [comment]
Thanks, I'll use that in the interim.
