### ISSUE TITLE
tests fail in a call to exit()

### ISSUE THREAD

**Issue by devoncarew** [flutter/tools#75]
The tests fail on a call to `exit(2)`: https://github.com/flutter/tools/blob/master/lib/src/device.dart#L135

We should mock out the exit function during tests, or have some other workaround; @iansf.

**Comment by iansf** [comment]
Ah -- so that's what's causing the failures...

**Comment by devoncarew** [comment]
Yeah, hard to see to because the tests had been running in parallel in different isolates (before I changed to `-j1`).

**Comment by devoncarew** [comment]
fixed by https://github.com/flutter/tools/pull/76
